config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#featured'

  resources :tokens, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      post :fetch_contract_details
    end
  end

  get '/styleguide' => "pages#styleguide"
  get '/unsubscription' => "unsubscription#new", as: :unsubscription

  resource :account, only: [:update]
  resources :wallets do
    member do
      get :algorand_opt_ins
      patch :make_primary
    end
  end
  resources :algorand_opt_ins, only: %i[index create]
  resources :accounts, only: [:new, :create, :show] do
    collection do
      get :download_data
      get :build_profile
      patch :update_profile
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  get '/account' => "accounts#show", as: :show_account
  get "accounts/confirm/:token" => "accounts#confirm", as: :confirm_email
  get "accounts/confirm-authentication/:token" => "accounts#confirm_authentication", as: :confirm_authentication
  get "/auth/slack/callback" => "sessions#create"
  post "/auth/slack" => "sessions#create", as: :login

  get "/auth/discord/callback" => "sessions#create"
  post "/auth/discord" => "sessions#create", as: :login_discord

  get '/logout', to: "sessions#destroy"

  get '/joinus' => "pages#join_us"
  get '/user-agreement' => "pages#user_agreement"
  get '/e-sign-disclosure' => "pages#e_sign_disclosure"
  get '/privacy-policy' => "pages#privacy_policy"
  get '/prohibited-use' => "pages#prohibited_use"
  get '/contribution_licenses/:type' => "pages#contribution_licenses", as: :contribution_licenses

  resource :session, only: %i[new create destroy] do
    get "oauth_failure"
    collection do
      post :sign_in
    end
  end
  get '/session' => "sessions#create"

  get '/tasks' => "awards#index", as: :my_tasks

  post '/slack/command' => "slack#command"

  get '/projects/mine' => "projects#landing", as: :my_project

  resources :projects do
    resources :award_types, path: 'batches', except: [:show] do
      resources :awards, path: 'tasks', except: [:index] do
        post :recipient_address
        post :send_award
        post :update_transaction_address
        get :clone
        get :award
        get :assignment
        post :assign
        post :start
        get :start
        post :submit
        post :accept
        post :reject
      end
    end
    resources :contributors, only: [:index]
    resources :interests, only: [:create, :destroy], defaults: { format: :json }

    namespace :dashboard do
      resources :transfers, only: [:index, :show, :create]
      resources :accounts, only: [:index, :show, :create] do
        collection do
          post :refresh_from_blockchain
        end
      end
      resources :accesses, only: [:index] do
        collection do
          post :regenerate_api_key
          post :add_admin
          delete :remove_admin
        end
      end
      resources :reg_groups, only: [:create, :update, :destroy]

      get 'transfer_categories', to: 'transfer_types#index', as: :transfer_categories

      resources :transfer_types, only: [:create, :update, :destroy]
      resources :transfer_rules, only: [:create, :destroy, :index] do
        collection do
          post :freeze
          post :refresh_from_blockchain
        end
      end
    end

    member do
      get :awards
    end

    collection do
      get :landing
      patch :update_status
    end
  end

  get '/p/:long_id' => "projects#unlisted", as: :unlisted_project
  get "awards/confirm/:token" => "awards#confirm", as: :confirm_award

  resources :teams, only: [:index] do
    member do
      get :channels
    end
  end

  resources :channels, only: [] do
    member do
      get :users
    end
  end

  resources :missions do
    collection do
      post :rearrange
    end
  end

  namespace :auth, defaults: { format: :json } do
    resources :eth, only: [:new, :create]

    post 'ore_id/new'
    delete 'ore_id/destroy'
    get 'ore_id/receive'
  end

  namespace :sign, defaults: { format: :json } do
    match 'ore_id/new', to: 'ore_id#new', via: [:get, :post]
    get 'ore_id/receive'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :accounts, only: [:show, :update, :create] do
        resources :interests, only: [:index, :create, :destroy]
        resources :verifications, only: [:index, :create]
        resources :wallets, only: [:index, :show, :create, :update, :destroy] do
          member do
            post :password_reset
          end
        end
        resources :transfers, only: [:index], controller: :account_transfers
        get :token_balances
      end

      resources :projects, only: [:show, :index] do
        resources :blockchain_transactions, only: [:create, :update, :destroy]
        resources :transfers, only: [:index, :show, :create, :destroy]
        resources :transfer_rules, only: [:index, :show, :create, :destroy]
        resources :reg_groups, only: [:index, :show, :create, :destroy]
        resources :hot_wallet_addresses, only: :create
      end

      resources :tokens, only: :index do
        resources :account_token_records, only: [:index, :create] do
          collection do
            delete :index, action: :destroy_all
          end
        end
      end

      namespace :wallet_recovery do
        get :public_wrapping_key
        post :recover
      end
    end
  end

  unless Rails.env.development? || Rails.env.test?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username.present? && password.present? &&
        username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
    end
  end
  mount Sidekiq::Web, at: "/admin/sidekiq"
end

app/controllers/api/v1/transfer_rules_controller.rb
class Api::V1::TransferRulesController < Api::V1::ApiController
  include Api::V1::Concerns::AuthorizableByProjectPolicy
  include Api::V1::Concerns::AuthorizableByMissionKey
  include Api::V1::Concerns::RequiresAnAuthorization

  # GET /api/v1/projects/1/transfer_rules
  def index
    fresh_when transfer_rules, public: true
  end

  # GET /api/v1/projects/1/transfer_rules/1
  def show
    fresh_when transfer_rule, public: true
  end

  # POST /api/v1/projects/1/transfer_rules
  def create
    transfer_rule = project.token.transfer_rules.create(transfer_rule_params)

    if transfer_rule.save
      @transfer_rule = transfer_rule

      render 'show.json', status: :created
    else
      @errors = transfer_rule.errors

      render 'api/v1/error.json', status: :bad_request
    end
  end

  # DELETE /api/v1/projects/1/transfer_rules/1
  def destroy
    transfer_rule.destroy
    render 'index.json', status: :ok
  end

  private

    def project
      @project ||= project_scope.find(params[:project_id])
    end

    def transfer_rules
      @transfer_rules ||= paginate(project.token.transfer_rules)
    end

    def transfer_rule
      @transfer_rule ||= project.token.transfer_rules.find(params[:id])
    end

    def transfer_rule_params
      params.fetch(:body, {}).fetch(:data, {}).fetch(:transfer_rule, {}).permit(
        :sending_group_id,
        :receiving_group_id,
        :lockup_until
      )
    end
end

app/controllers/dashboard/accesses_controller.rb
class Dashboard::AccessesController < ApplicationController
  before_action :assign_project
  skip_after_action :verify_policy_scoped, only: [:index]

  fragment_cache_key do
    "#{current_user&.id}/#{@project.id}/#{@project.token&.updated_at}"
  end

  def index
    authorize @project, :accesses?

    @admins = @project.admins
  end

  def add_admin
    authorize @project
    account =
      if @whitelabel_mission
        @whitelabel_mission.managed_accounts.find_by email: params[:email]
      else
        Account.find_by(email: params[:email], managed_mission_id: nil)
      end

    return redirect_to project_dashboard_accesses_path(@project), flash: { error: 'Account is not found on CoMakery' } unless account

    return redirect_to project_dashboard_accesses_path(@project), flash: { error: 'Project owner cannot be added as a project admin' } if @project.account == account

    return redirect_to project_dashboard_accesses_path(@project), flash: { error: "#{account.decorate.name} is already a project admin" } if @project.admins.include?(account)

    @project.admins << account
    @project.interested << account unless account.interested?(@project.id)
    redirect_to project_dashboard_accesses_path(@project), notice: "#{account.decorate.name} added as a project admin"
  end

  def remove_admin
    authorize @project

    account = Account.find_by(id: params[:account_id])

    if account && @project.admins.include?(account)
      @project.admins.delete(account)
      redirect_to project_dashboard_accesses_path(@project), notice: "#{account.decorate.name} removed from project admins"
    else
      redirect_to project_dashboard_accesses_path(@project), flash: { error: 'Project admin is not found' }
    end
  end

  def regenerate_api_key
    authorize @project

    @project.regenerate_api_key

    redirect_to project_dashboard_accesses_path(@project), notice: 'API key has been regenerated'
  end
end

app/controllers/dashboard/accounts_controller.rb
class Dashboard::AccountsController < ApplicationController
  before_action :assign_project
  before_action :normalize_account_token_records_lockup_until_lt, only: [:index]
  before_action :set_accounts, only: [:index]
  before_action :authorize_project, only: :create
  skip_before_action :require_login, only: %i[index show]
  skip_after_action :verify_policy_scoped, only: %i[index create]

  fragment_cache_key do
    "#{current_user&.id}/#{@project.id}/#{@project.token&.updated_at}"
  end

  def index
    authorize @project, :accounts?
  end

  def create
    authorize @project, :edit_accounts?

    account_token_record = @project.token.account_token_records.new(account_token_record_params)
    account_token_record.account_id = params.dig(:account_token_record, :account_id)
    account_token_record.lockup_until = Time.zone.parse(account_token_record_params[:lockup_until])

    if account_token_record.save
      if account_token_record.token.blockchain.supported_by_ore_id?
        redirect_to sign_ore_id_new_path(account_token_record_id: account_token_record.id)
      else
        @account_token_record = account_token_record

        render 'api/v1/account_token_records/show.json', status: :created
      end
    else
      @errors = account_token_record.errors

      render 'api/v1/error.json', status: :bad_request
    end
  end

  def show
    authorize @project, :accounts?

    account = @project.interested.find(params[:id])

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("project_#{@project.id}_account_#{account.id}", partial: 'dashboard/accounts/account',
                                                                                                  locals: { account: account })
      end

      format.html { redirect_to root_path }
    end
  end

  def refresh_from_blockchain
    authorize @project, :accounts?

    if @project.token.account_token_records.fresh?
      notice = 'Accounts were already synced'
    else
      @project.token.token_type.accounts_sync_job&.perform_now(@project.token)

      notice = 'Accounts were synced from the blockchain'
    end

    redirect_to project_dashboard_accounts_path(@project), notice: notice
  end

  private

    def normalize_account_token_records_lockup_until_lt
      t = params.fetch(:q, {}).fetch(:account_token_records_lockup_until_lt, nil)
      params[:q][:account_token_records_lockup_until_lt] = Time.zone.parse(t)&.to_i if t
    end

    def set_accounts
      @page = (params[:page] || 1).to_i
      @q = @project.interested
                   .joins('inner join projects on projects.id = interests.project_id')
                   .joins('inner join account_token_records on account_token_records.token_id = projects.token_id and account_token_records.account_id = accounts.id')
                   .includes(
                     :verifications,
                     :awards,
                     :latest_verification,
                     account_token_records: [:reg_group]
                   ).ransack(params[:q])

      @accounts_all = @q.result
      @accounts_all.size
      @accounts = @accounts_all.page(@page).per(10)
      redirect_to '/404.html' if (@page > 1) && @accounts.out_of_range?
    rescue ActiveRecord::StatementInvalid
      head 404
    end

    def authorize_project
      authorize @project, :edit?
    end

    def account_token_record_params
      params.fetch(:account_token_record, {}).permit(
        :max_balance,
        :lockup_until,
        :reg_group_id,
        :account_frozen
      )
    end
end

app/controllers/dashboard/reg_groups_controller.rb
class Dashboard::RegGroupsController < ApplicationController
  before_action :assign_project
  before_action :set_reg_group, only: %i[update destroy]

  fragment_cache_key do
    "#{current_user&.id}/#{@project.id}/#{@project.token&.updated_at}"
  end

  def create
    authorize @project, :edit_reg_groups?

    @reg_group = @project.token.reg_groups.new(reg_group_params)

    if @reg_group.save
      redirect_to project_dashboard_transfer_rules_path(@project), notice: 'Group created'
    else
      redirect_to project_dashboard_transfer_rules_path(@project), flash: { error: @reg_group.errors.full_messages.join(', ') }
    end
  end

  def update
    authorize @project, :edit_reg_groups?

    if @reg_group.update(reg_group_params)
      redirect_to project_dashboard_transfer_rules_path(@project), notice: 'Group updated'
    else
      redirect_to project_dashboard_transfer_rules_path(@project), flash: { error: @reg_group.errors.full_messages.join(', ') }
    end
  end

  def destroy
    authorize @project, :edit_reg_groups?

    if @reg_group.destroy
      redirect_to project_dashboard_transfer_rules_path(@project), notice: 'Group destroyed'
    else
      redirect_to project_dashboard_transfer_rules_path(@project), flash: { error: @reg_group.errors.full_messages.join(', ') }
    end
  end

  private

    def set_reg_group
      @reg_group = @project.token.reg_groups.find(params[:id])
    end

    def reg_group_params
      params.fetch(:reg_group, {}).permit(
        :name,
        :blockchain_id
      )
    end
end

app/controllers/dashboard/transfer_rules_controller.rb
class Dashboard::TransferRulesController < ApplicationController
  before_action :assign_project
  before_action :set_reg_groups, only: [:index]
  before_action :set_transfer_rules, only: [:index]
  before_action :set_transfer_rule, only: [:destroy]
  skip_before_action :require_login, only: [:index]
  skip_after_action :verify_policy_scoped, only: [:index]

  fragment_cache_key do
    "#{current_user&.id}/#{@project.id}/#{@project.token&.updated_at}"
  end

  def index
    authorize @project, :show_transfer_rules?
  end

  def create
    authorize @project, :edit_transfer_rules?

    transfer_rule = @project.token.transfer_rules.new(transfer_rule_params)
    transfer_rule.lockup_until = Time.zone.parse(transfer_rule_params[:lockup_until])

    if transfer_rule.save
      redirect_to sign_ore_id_new_path(transfer_rule_id: transfer_rule.id)
    else
      redirect_to project_dashboard_transfer_rules_path(@project), flash: { error: transfer_rule.errors.full_messages.join(', ') }
    end
  end

  def destroy
    authorize @project, :edit_transfer_rules?
    transfer_rule = @transfer_rule.dup
    transfer_rule.lockup_until = 0
    transfer_rule.status = nil
    transfer_rule.save!

    redirect_to sign_ore_id_new_path(transfer_rule_id: transfer_rule.id)
  end

  def freeze
    authorize @project, :freeze_token?
    redirect_to sign_ore_id_new_path(token_id: @project.token.id)
  end

  def refresh_from_blockchain
    authorize @project, :refresh_transfer_rules?

    if @project.token.transfer_rules.fresh?
      notice = 'Transfer rules were already synced'
    else
      @project.token.token_type.transfer_rule_sync_job&.perform_now(@project.token)
      notice = 'Transfer rules were synced from the blockchain'
    end

    redirect_to project_dashboard_transfer_rules_path(@project), notice: notice
  end

  private

    def set_reg_groups
      @reg_groups = @project.token.reg_groups.order(:blockchain_id)
    end

    def set_transfer_rules
      @page = (params[:page] || 1).to_i
      @q = @project.token.transfer_rules.ransack(params[:q])
      @transfer_rules_all = @q.result.includes(:sending_group, :receiving_group)
      @transfer_rules = @transfer_rules_all.page(@page).per(10)
      redirect_to '/404.html' if (@page > 1) && @transfer_rules.out_of_range?
    end

    def set_transfer_rule
      @transfer_rule = @project.token.transfer_rules.find(params[:id])
    end

    def transfer_rule_params
      params.fetch(:transfer_rule, {}).permit(
        :sending_group_id,
        :receiving_group_id,
        :lockup_until
      )
    end
end

app/views/dashboard/transfer_rules/_form_reg_group.html.erb
<%= form_with model: RegGroup.new(token: @project.token), url: project_dashboard_reg_groups_path(@project), class: 'reg-groups__form', data: { target: 'reg-group-form.form' } do |f| %>
  <%= f.text_field(:name, required: true, placeholder: 'Group Name') %>
  <%= f.number_field(:blockchain_id, required: true, placeholder: 'ID', min: 0, readonly: true) %>
  <%= f.submit('create') %>
  <%= button_tag "cancel", type: 'button', data: {action: 'reg-group-form#hideForm'} %>
<% end %>

app/views/dashboard/transfer_rules/_form_transfer_rule.html.erb
<%= form_with(TransferRule.new.decorate.form_attrs(@project)) do |f| %>
  <%= image_tag 'iconCloseDark.svg', data: {action: 'click->transfer-rules#hideForm'}, class: 'transfers-table--edit-icon' %>

  <div class="transfers-table__transfer">
    <div class="transfers-table__transfer__sending_group">
      <label>sending group</label>

      <%= f.select(:sending_group_id, @project.token.reg_groups.collect { |g| [ "#{g.name} (#{g.blockchain_id})", g.id ] }, { include_blank: 'Select Group' }, { required: true, data: {target: "transfer-rule-form.ruleFromGroupId transfer-rule-form.inputs"} }) %>
    </div>

    <div class="transfers-table__transfer__sending_group_id">
    </div>

    <div class="transfers-table__transfer__receiving_group">
      <label>receiving group</label>

      <%= f.select(:receiving_group_id, @project.token.reg_groups.collect { |g| [ "#{g.name} (#{g.blockchain_id})", g.id ] }, { include_blank: 'Select Group' }, { required: true, data: {target: "transfer-rule-form.ruleToGroupId transfer-rule-form.inputs"} }) %>
    </div>

    <div class="transfers-table__transfer__receiving_group_id">
    </div>

    <div class="transfers-table__transfer__lockup_until">
      <label>allowed after date</label>

      <%= f.datetime_local_field(:lockup_until, step: 1, required: true, placeholder: 'dd.mm.yyyy', data: {target: "transfer-rule-form.ruleLockupUntil transfer-rule-form.inputs"}) %>
    </div>

    <% if policy(@project).edit_transfer_rules? %>
      <div class="transfers-table__transfer__action">
        <div class='transfer-button'>
          <% if @project.token.token_frozen? %>
            frozen
          <% elsif @project.token.blockchain.supported_by_ore_id? %>
            <%= f.button type: :submit, class: 'transfer-algo-btn', data: { turbo: "false" } do %>
              <%= render partial: "shared/wallet_logo", locals: { project: @project, size: 12 } %>
              <span>SAVE</span>
            <% end %>
          <% else %>
            <%= link_to 'javascript:void(0)', data: {action: 'transfer-rule-form#create', target: 'transfer-rule-form.button'}, class: 'transfer-tokens-btn transfer-tokens-btn-skip-legacy' do %>
              <%= render partial: "shared/wallet_logo", locals: { project: @project, size: 12 } %>
              <span>Create</span>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/dashboard/transfer_rules/_freeze_token.html.erb
<div class="freeze-token">
  <% if @project.token.blockchain.supported_by_ore_id? %>
    <%= button_to freeze_project_dashboard_transfer_rules_path(@project), class: 'transfer-algo-btn transfer-tokens-btn-freeze', data: { turbo: "false" } do %>
      <%= render partial: "shared/wallet_logo", locals: { project: @project, size: 12 } %>
      <span><%= @project.token.token_frozen? ? 'Unfreeze' : 'Freeze' %></span>
    <% end %>
  <% else %>
    <%= form_with url: freeze_project_dashboard_transfer_rules_path(@project), data: {controller: "freeze-form", target: "freeze-form.form"}.merge(@project.token.decorate.eth_data('freeze-form')), class: 'freeze-token__form transfer-button' do |f| %>
      <%= link_to 'javascript:void(0)', data: {action: 'click->freeze-form#unpause', target: 'freeze-form.button'}, class: 'transfer-tokens-btn transfer-tokens-btn-skip-legacy transfer-tokens-btn-freeze' do %>
        <%= render partial: "shared/wallet_logo", locals: { project: @project, size: 12 } %>
        <span><%= @project.token.token_frozen? ? 'Unfreeze' : 'Freeze' %></span>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/dashboard/transfer_rules/_frozen_status.html.erb
<div class="frozen-status" data-controller="comakery-security-token">
  <h2>transfer status</h2>

  <h3><%= @project.token&.token_frozen ? 'Frozen' : 'Not Frozen' %></h3>

  <% if policy(@project).freeze_token? %>
    <%= render partial: "freeze_token" %>
  <% end %>
</div>

app/views/dashboard/transfer_rules/_header.html.erb
<div class="transfers-table__transfer transfers-table__transfer--header">
  <label>sort by</label>

  <div class="transfers-table__transfer__sending_group">
    <%= sort_link(@q, :sending_group_name, 'sending group') %>
  </div>

  <div class="transfers-table__transfer__sending_group_id">
    <%= sort_link(@q, :sending_group_blockchain_id, 'id') %>
  </div>

  <div class="transfers-table__transfer__receiving_group">
    <%= sort_link(@q, :receiving_group_name, 'receiving group') %>
  </div>

  <div class="transfers-table__transfer__receiving_group_id">
    <%= sort_link(@q, :receiving_group_blockchain_id, 'id') %>
  </div>

  <div class="transfers-table__transfer__lockup_until">
    <%= sort_link(@q, :lockup_until, 'allowed after date') %>
  </div>

  <% if policy(@project).edit_transfer_rules? %>
    <div class="transfers-table__transfer__action">
    </div>
  <% end %>
</div>

app/views/dashboard/transfer_rules/_reg_group.html.erb
<div class="reg-groups__groups__group" data-controller="reg-group-edit-form">
  <h4 data-target="reg-group-edit-form.show"><%= reg_group.name %></h4>
  <span data-target="reg-group-edit-form.show">ID:<%= reg_group.blockchain_id %></span>

  <% if policy(@project).edit_reg_groups? %>
    <%= image_tag 'pencil.svg', size: "14x14", alt: "edit group", data: {target: 'reg-group-edit-form.show', action: 'click->reg-group-edit-form#showForm'} %>

    <%= form_with model: reg_group, url: project_dashboard_reg_group_path(project_id: @project.id, id: reg_group.id), class: 'reg-groups__form reg-groups__form--edit hidden', data: { target: 'reg-group-edit-form.form' } do |f| %>
      <%= f.text_field(:name, required: true, placeholder: 'Group Name') %>
      <%= f.number_field(:blockchain_id, required: true, placeholder: 'ID', min: 0, readonly: true) %>
      <%= f.submit('save', data: {confirm: 'Update group?'}) %>
      <%= button_tag "cancel", type: 'button', data: {action: 'reg-group-edit-form#hideForm'} %>
    <% end %>

    <%= link_to(project_dashboard_reg_group_path(project_id: @project.id, id: reg_group.id), method: :delete, data: {confirm: "Remove #{reg_group.name} group?", target: 'reg-group-edit-form.show'} ) do %>
      <%= image_pack_tag 'media/src/images/styleguide/icons/iconTrash.svg', size: "14x14", alt: "remove group" %>
    <% end %>
  <% end %>
</div>

app/views/dashboard/transfer_rules/_reg_groups.html.erb
<div class="reg-groups" data-controller="reg-group-form">
  <h2>regulatory groups</h2>

  <h3><%= pluralize(@reg_groups.size, 'Group', 'Groups') %></h3>

  <div class="reg-groups__create">
    <% if policy(@project).edit_reg_groups? %>
      <%= button_tag "create reg group ＋", type: 'button', class: 'reg-groups-create', data: { target: 'reg-group-form.create', action: 'reg-group-form#showForm' } %>
    <% end %>
  </div>

  <div class="reg-groups__groups">
    <%= render partial: "reg_group", collection: @reg_groups, as: :reg_group, cached: true %>
  </div>

  <%= render partial: "form_reg_group" %>
</div>

app/views/dashboard/transfer_rules/_transfer_rule.html.erb
<%= form_with(transfer_rule.decorate.form_attrs_del(@project)) do |f| %>
  <div class="transfers-table__transfer <%= transfer_rule.synced? ? nil : 'transfers-table__transfer--processing' %>">
    <div class="transfers-table__transfer__sending_group">
      <label>sending group</label>

      <%= transfer_rule.sending_group.name %>
    </div>

    <div class="transfers-table__transfer__sending_group_id">
      <label>sending group id</label>

      <%= transfer_rule.sending_group.blockchain_id %>
    </div>

    <div class="transfers-table__transfer__receiving_group">
      <label>receiving group</label>

      <%= transfer_rule.receiving_group.name %>
    </div>

    <div class="transfers-table__transfer__receiving_group_id">
      <label>receiving group id</label>

      <%= transfer_rule.receiving_group.blockchain_id %>
    </div>

    <div class="transfers-table__transfer__lockup_until">
      <label>allowed after date</label>

      <%= transfer_rule.decorate.lockup_until_pretty %>
    </div>

    <% if policy(@project).edit_transfer_rules? %>
      <div class="transfers-table__transfer__action transfers-table__transfer__action--warn">
        <div class="transfer-button <%= transfer_rule.synced? ? nil : 'in-progress--metamask in-progress--metamask__paid' %>">
          <% if @project.token&.token_frozen? %>
            frozen
          <% elsif @project.token.blockchain.supported_by_ore_id? %>
            <%= f.button type: :submit, class: 'transfer-algo-btn', data: { turbo: "false" } do %>
              <%= render partial: "shared/wallet_logo", locals: { project: @project, size: 12 } %>
              <span><%= transfer_rule.synced? ? 'DELETE' : 'PROCESSING' %></span>
            <% end %>
          <% else %>
            <%= link_to 'javascript:void(0)', data: {action: 'transfer-rule-form#delete', target: 'transfer-rule-form.button'}, class: 'transfer-tokens-btn transfer-tokens-btn-skip-legacy' do %>
              <%= render partial: "shared/wallet_logo", locals: { project: @project, size: 12 } %>
              <span><%= transfer_rule.synced? ? 'Reset' : 'Processing' %></span>
            <% end %>

          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/dashboard/transfer_rules/_transfer_rules.html.erb
<div class="transfer-rules" data-controller="transfer-rules">
  <h2>transfer rules</h2>

  <h3><%= pluralize(@transfer_rules_all.size, 'Rule', 'Rules') %></h3>

  <div class="transfer-rules__buttons">
    <div class="transfer-rules__create">
      <% if policy(@project).edit_transfer_rules? && @project.token.token_type.transfer_rule_sync_job %>
        <%= button_tag "create transfer rule ＋", type: 'button', class: 'transfer-rule-create', data: { target: 'transfer-rules.button', action: 'transfer-rules#showForm' } %>
      <% end %>
    </div>

    <div class="transfer-rules__refresh_from_blockchain">
      <% if policy(@project).refresh_transfer_rules? %>
        <%= button_to 'refresh transfer rules', refresh_from_blockchain_project_dashboard_transfer_rules_path(@project), class: 'transfer-rules__refresh_from_blockchain_button', method: :post, disabled: @project.token.transfer_rules.fresh?, data: { disable_with: "..." } %>
      <% end %>
    </div>
  </div>

  <div class="transfer-rules__table transfers-table">
    <%= render partial: "header" %>
    <%= render partial: "form_transfer_rule" %>
    <%= render partial: "transfer_rule", collection: @transfer_rules, as: :transfer_rule, cached: false %>
  </div>

  <div class="transfers-pages">
    <%= paginate(@transfer_rules, window: 3) %>
  </div>
</div>

app/views/dashboard/transfer_rules/index.html.erb
<%= render layout: 'projects/project_settings' do %>
  <%= render partial: "reg_groups" %>
  <%= render partial: "transfer_rules" %>
  <%= render partial: "frozen_status" %>
<% end %>