config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#featured'

  resources :tokens, only: [:index, :new, :create, :show, :edit, :update] do
    collection do
      post :fetch_contract_details
    end
  end

  get '/styleguide' => "pages#styleguide"
  get '/unsubscription' => "unsubscription#new", as: :unsubscription

  resource :account, only: [:update]
  resources :wallets do
    member do
      get :algorand_opt_ins
      patch :make_primary
    end
  end
  resources :algorand_opt_ins, only: %i[index create]
  resources :accounts, only: [:new, :create, :show] do
    collection do
      get :download_data
      get :build_profile
      patch :update_profile
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  get '/account' => "accounts#show", as: :show_account
  get "accounts/confirm/:token" => "accounts#confirm", as: :confirm_email
  get "accounts/confirm-authentication/:token" => "accounts#confirm_authentication", as: :confirm_authentication
  get "/auth/slack/callback" => "sessions#create"
  post "/auth/slack" => "sessions#create", as: :login

  get "/auth/discord/callback" => "sessions#create"
  post "/auth/discord" => "sessions#create", as: :login_discord

  get '/logout', to: "sessions#destroy"

  get '/joinus' => "pages#join_us"
  get '/user-agreement' => "pages#user_agreement"
  get '/e-sign-disclosure' => "pages#e_sign_disclosure"
  get '/privacy-policy' => "pages#privacy_policy"
  get '/prohibited-use' => "pages#prohibited_use"
  get '/contribution_licenses/:type' => "pages#contribution_licenses", as: :contribution_licenses

  resource :session, only: %i[new create destroy] do
    get "oauth_failure"
    collection do
      post :sign_in
    end
  end
  get '/session' => "sessions#create"

  get '/tasks' => "awards#index", as: :my_tasks

  post '/slack/command' => "slack#command"

  get '/projects/mine' => "projects#landing", as: :my_project

  resources :projects do
    resources :award_types, path: 'batches', except: [:show] do
      resources :awards, path: 'tasks', except: [:index] do
        post :recipient_address
        post :send_award
        post :update_transaction_address
        get :clone
        get :award
        get :assignment
        post :assign
        post :start
        get :start
        post :submit
        post :accept
        post :reject
      end
    end
    resources :contributors, only: [:index]
    resources :interests, only: [:create, :destroy], defaults: { format: :json }

    namespace :dashboard do
      resources :transfers, only: [:index, :show, :create]
      resources :accounts, only: [:index, :show, :create] do
        collection do
          post :refresh_from_blockchain
        end
      end
      resources :accesses, only: [:index] do
        collection do
          post :regenerate_api_key
          post :add_admin
          delete :remove_admin
        end
      end
      resources :reg_groups, only: [:create, :update, :destroy]

      get 'transfer_categories', to: 'transfer_types#index', as: :transfer_categories

      resources :transfer_types, only: [:create, :update, :destroy]
      resources :transfer_rules, only: [:create, :destroy, :index] do
        collection do
          post :freeze
          post :refresh_from_blockchain
        end
      end
    end

    member do
      get :awards
    end

    collection do
      get :landing
      patch :update_status
    end
  end

  get '/p/:long_id' => "projects#unlisted", as: :unlisted_project
  get "awards/confirm/:token" => "awards#confirm", as: :confirm_award

  resources :teams, only: [:index] do
    member do
      get :channels
    end
  end

  resources :channels, only: [] do
    member do
      get :users
    end
  end

  resources :missions do
    collection do
      post :rearrange
    end
  end

  namespace :auth, defaults: { format: :json } do
    resources :eth, only: [:new, :create]

    post 'ore_id/new'
    delete 'ore_id/destroy'
    get 'ore_id/receive'
  end

  namespace :sign, defaults: { format: :json } do
    match 'ore_id/new', to: 'ore_id#new', via: [:get, :post]
    get 'ore_id/receive'
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :accounts, only: [:show, :update, :create] do
        resources :interests, only: [:index, :create, :destroy]
        resources :verifications, only: [:index, :create]
        resources :wallets, only: [:index, :show, :create, :update, :destroy] do
          member do
            post :password_reset
          end
        end
        resources :transfers, only: [:index], controller: :account_transfers
        get :token_balances
      end

      resources :projects, only: [:show, :index] do
        resources :blockchain_transactions, only: [:create, :update, :destroy]
        resources :transfers, only: [:index, :show, :create, :destroy]
        resources :transfer_rules, only: [:index, :show, :create, :destroy]
        resources :reg_groups, only: [:index, :show, :create, :destroy]
        resources :hot_wallet_addresses, only: :create
      end

      resources :tokens, only: :index do
        resources :account_token_records, only: [:index, :create] do
          collection do
            delete :index, action: :destroy_all
          end
        end
      end

      namespace :wallet_recovery do
        get :public_wrapping_key
        post :recover
      end
    end
  end

  unless Rails.env.development? || Rails.env.test?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username.present? && password.present? &&
        username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
    end
  end
  mount Sidekiq::Web, at: "/admin/sidekiq"
end

app/views/shared/_meta_tags.html.erb
<% if @whitelabel_mission %>
  <% title = @meta_title ? @meta_title : @whitelabel_mission.name %>
  <% description = @meta_desc ? @meta_desc : nil %>
  <% image = @meta_image ? @meta_image : nil %>
  <% url = url_for(only_path: false) %>
<% else %>
  <% title = @meta_title ? @meta_title : 'CoMakery - Achieve Big Missions' %>
  <% description = @meta_desc ? @meta_desc : 'Built from a belief in the power of people, together. With CoMakery, you can gather or join a tribe and work to achieve big missions.' %>
  <% image = @meta_image ? @meta_image : '/comakery.jpg' %>
  <% url = url_for(only_path: false) %>
<% end %>

<meta content='text/html; charset=UTF-8' http-equiv='Content-Type'>
<meta charset='utf-8'>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name='robots' content='NOODP'>
<meta name='theme-color' content='#ffffff'>
<meta name='msapplication-TileColor' content='#ffffff'>
<meta name='msapplication-TileImage' content='/assets/favicon/ms-icon-144x144.png'>

<title><%= title %></title>
<meta name="title" content="<%= title %>">
<meta name="description" content="<%= description %>">

<meta property="og:type" content="website">
<meta property="og:url" content="<%= url %>">
<meta property="og:title" content="<%= title %>">
<meta property="og:description" content="<%= description %>">
<meta property="og:image" content="<%= image %>">

<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="<%= url %>">
<meta property="twitter:title" content="<%= title %>">
<meta property="twitter:description" content="<%= description %>">
<meta property="twitter:image" content="<%= image %>">

<meta name="turbo-cache-control" content="no-preview">

<% if @whitelabel_mission && @whitelabel_mission&.whitelabel_favicon %>
  <% cache @whitelabel_mission do %>
    <link rel="shortcut icon" type="image/png"
          href="<%= Attachment::GetPath.call(attachment: @whitelabel_mission.whitelabel_favicon, resize_to_fill: [64, 64]).path %>">
  <% end %>
<% else %>
  <%= favicon_link_tag 'favicon/favicon.ico', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-57x57.png', rel: 'apple-touch-icon', sizes: '57x57', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-60x60.png', rel: 'apple-touch-icon', sizes: '60x60', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-72x72.png', rel: 'apple-touch-icon', sizes: '72x72', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-76x76.png', rel: 'apple-touch-icon', sizes: '76x76', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-114x114.png', rel: 'apple-touch-icon', sizes: '114x114', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-120x120.png', rel: 'apple-touch-icon', sizes: '120x120', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-144x144.png', rel: 'apple-touch-icon', sizes: '144x144', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-152x152.png', rel: 'apple-touch-icon', sizes: '152x152', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/apple-icon-180x180.png', rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/android-icon-192x192.png', rel: 'icon', sizes: '192x192', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/favicon-32x32.png', rel: 'icon', sizes: '32x32', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/favicon-96x96.png', rel: 'icon', sizes: '96x96', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/favicon-16x16.png', rel: 'icon', sizes: '16x16', type: 'image/png', defer: true %>
  <%= favicon_link_tag 'favicon/manifest.json', rel: 'manifest', type: 'application/json', defer: true %>
<% end %>

app/views/shared/_p.html.erb
<div class="paragraph">
  <% if defined? title %>
    <div class="paragraph__title">
      <%= title %>
    </div>
  <% end %>

  <div class="paragraph__content">
    <%= yield %>
  </div>
</div>

app/views/shared/_transfer_button.html.erb
<div class="transfer-button <%= transfer.decorate.transfer_button_state_class %>">
  <% if transfer.project.token&._token_type? %>
    <% if transfer.paid? && transfer.ethereum_transaction_explorer_url %>
      <%= link_to transfer.ethereum_transaction_address_short, transfer.ethereum_transaction_explorer_url, target: '_blank' %>

    <% elsif transfer.paid? %>
      paid

    <% elsif transfer.project.token&.token_frozen? %>
      frozen

    <% elsif transfer.recipient_address.blank? && current_account == transfer.account %>
      <%= link_to 'needs wallet', account_path %>
    <% elsif transfer.token&.blockchain&.supported_by_ore_id? && (transfer.issuer&.ore_id_account.nil? || transfer.account&.ore_id_account.nil?) %>
      <%= link_to 'needs wallet', account_path %>
    <% elsif transfer.recipient_address.blank? %>
      needs wallet

    <% elsif current_account&.decorate&.can_send_awards?(transfer.project) && transfer.accepted? %>
      <% if transfer.token.blockchain.supported_by_ore_id? %>
        <%= button_to sign_ore_id_new_path(transfer_id: transfer.id), class: 'transfer-algo-btn', rel: 'nofollow', method: :post, data: {turbo: "false"} do %>
            <%= render partial: "shared/wallet_logo", locals: { project: transfer.project, size: 12 } %>
            <span>PAY</span>
        <% end %>
      <% else %>
        <%= link_to 'javascript:void(0)', class: "transfer-tokens-btn", data: transfer.decorate.pay_data do %>
          <%= render partial: "shared/wallet_logo", locals: { project: transfer.project, size: 12 } %>

          <% case transfer.latest_blockchain_transaction&.status %>
          <% when 'created' %>
            <% if transfer.latest_blockchain_transaction&.waiting_in_created? %>
              <span>processing</span>
            <% else %>
              <span><%= transfer.decorate.transfer_button_text %></span>
            <% end %>
          <% when 'pending' %>
            <span>processing</span>
          <% when 'cancelled', 'failed' %>
            <span title="Last Failure: <%= transfer.latest_blockchain_transaction&.status_message %>">retry</span>
          <% else %>
            <span><%= transfer.decorate.transfer_button_text %></span>
          <% end %>
        <% end %>
      <% end %>

    <% elsif transfer.cancelled? %>
      cancelled
    <% else %>
      pending
    <% end %>
  <% end %>
</div>

app/views/shared/_wallet_logo.html.erb
<% if project.token&.token_type&.wallet_logo %>
  <div class="wallet-logo">
    <%= image_tag project.token&.token_type&.wallet_logo, size: "#{size}x#{size}" %>
  </div>
<% end %>

app/views/shared/_wallets.html.erb
<%= javascript_include_tag Webpacker.manifest.lookup!('wallets/qrc20_qweb3_script.js') if @project.token&._token_type_qrc20? %>
<%= javascript_include_tag Webpacker.manifest.lookup!('wallets/cardano_trezor_script.js') if @project.token&._token_type_ada? %>
<%= javascript_include_tag Webpacker.manifest.lookup!('wallets/bitcoin_trezor_script.js') if @project.token&._token_type_btc? %>
<%= javascript_include_tag Webpacker.manifest.lookup!('wallets/qtum_ledger_script.js') if @project.token&._token_type_qtum? %>
<%= javascript_include_tag Webpacker.manifest.lookup!('wallets/eos_scatter_script.js') if @project.token&._token_type_eos? %>
<%= javascript_include_tag 'eztz.min' if @project.token&._token_type_xtz? %>
<%= javascript_include_tag '//connect.trezor.io/6/trezor-connect.js' if @project.token&._token_type_xtz? %>
<%= javascript_include_tag Webpacker.manifest.lookup!('wallets/tezos_trezor_script.js') if @project.token&._token_type_xtz? %>